apiVersion: v1 # Specifies the API version for the Service resource.
kind: Service # Defines the resource type as a Service.
metadata: 
  name: loadbalancer-service # Name of the Service.
spec: 
  type: LoadBalancer # Exposes the Service externally using a cloud provider's load balancer.
  selector: 
    name: busybox-pod # Matches Pods with this label.
  ports: 
    - port: 80 # Port on which the Service is exposed.
      targetPort: 8080 # Port on the container to which traffic is forwarded.
