apiVersion: v1 # Specifies the API version for the Service resource.
kind: Service # Defines the resource type as a Service.
metadata: 
  name: clusterip-service # Name of the Service.
spec: 
  type: ClusterIP # Default type, exposes the Service only within the cluster.
  selector: 
    name: busybox-pod # Matches Pods with this label.
  ports: 
    - port: 80 # Port on which the Service is exposed.
      targetPort: 8080 # Port on the container to which traffic is forwarded.
